config/routes.rb
Rails.application.routes.draw do
	get '/todos/:id/task_done', to: 'todos#complete', as: :task_done
	get '/todos/list', to: 'todos#list', as: :task_list
	resources :todos

  #Realice las mismas rutas mostradas en los videos de las clases online y no me resultaban. Revise la guia Rails y aplique resource
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
	validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController

	def index
		@todos = Todo.all
	end

	def new
		@todo = Todo.new
	end

	def create
		@todo = Todo.new(todo_params)
		if @todo.save
			redirect_to todos_path
		else
			render 'new'
		end
	end

	def show
		@todo = Todo.find(params[:id])
	end

	def edit
		@todo = Todo.find(params[:id])
	end

	def update
		@todo = Todo.find(params[:id])
		if @todo.update(todo_params)
			redirect_to todos_path
		else
			render 'edit'
		end
	end

	def destroy
		@todo = Todo.find(params[:id])
		@todo.destroy
		redirect_to todos_path
	end

	def complete
		@todo = Todo.find(params[:id])
		@todo.update(completed: true)
		redirect_to todos_path
	end

	def list
		@todos = Todo.all
	end

	private
	def todo_params
		params.require(:todo).permit(:title, :description)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
  </head>

  <body>
  	<%= render '/todos/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/todos/_form.html.erb
<%= form_with model: @todo, local: true do |form| %>
<% if @todo.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@todo.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @todo.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form.label 'Asunto' %>
  <%= form.text_field :title %>
  <%= form.label 'Descripción' %>
  <%= form.text_area :description %>
  <%= form.submit %>
<% end %>

app/views/todos/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">ಠ_ಠ ToDos |</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Ver ToDos", todos_path, class: "nav-link" %>
        <!--<a class="nav-link" href="#"> Index <span class="sr-only">(current)</span></a>-->
      </li>
      <li class="nav-item">
        <%= link_to "Terminados vs. Pendientes", task_list_path, class: "nav-link" %>
        <!--<a class="nav-link" href=link_to "Lista">Lista de Tareas</a>-->
      </li>
      <li class="nav-item">
        <%= link_to "Crear un nuevo ToDo", new_todo_path, class: "nav-link" %>
        <!--<a class="nav-link" href="#">Crear nueva Tarea</a>-->
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="Buscar" placeholder="Buscar" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Buscar</button>
    </form>
  </div>
</nav>

app/views/todos/edit.html.erb
<h1> Editar una tarea pendiente ʕºᴥºʔ </h1>

<%= render 'form' %>

app/views/todos/index.html.erb
<h1> Lista de Pendientes ( ͡° ͜ʖ ͡°) </h1>

<div class="well well-lg">Esto es una lista de hueás pendientes
	<table>
		<tr>
			<th> Título </th>
			<th> Descripción </th>
		</tr>
		<% @todos.each do |todo| %>
		<tr>
			<td> <%= todo.title %> </td>
			<td> <%= todo.description %> </td>
			<td> <%= link_to "Ver", todo_path(todo.id) %> </td>
			<td> <%= link_to "Editar", edit_todo_path(todo.id) %> </td>
			<td> <%= link_to "Eliminar", todo_path(todo.id), method: :delete, data: { confirm: '¿Estás seguro de eliminar tarea?'} %> </td>
			<td> <%= link_to "Terminar tarea", task_done_path(todo.id) %> </td>
		</tr>
		<% end %>
	</table>
</div>

<%= link_to "Crear ToDo", new_todo_path %>

app/views/todos/list.html.erb
<div class="row">
  <div class="col-6">
  	<h1>Pendientes :'(</h1>
  	<table>
		<tr>
			<th> Título </th>
			<th> Descripción </th>
		</tr>
		<% @todos.where(completed: nil).each do |todo| %>
		<tr>
			<td> <%= todo.title %> </td>
			<td> <%= todo.description %> </td>
			<td> <%= link_to "Ver", todo_path(todo.id) %> </td>
			<td> <%= link_to "Editar", edit_todo_path(todo.id) %> </td>
			<td> <%= link_to "Eliminar", todo_path(todo.id), method: :delete, data: { confirm: '¿Estás seguro de eliminar tarea?'} %> </td>
			<td> <%= link_to "Terminar tarea", task_done_path(todo.id) %> </td>
		</tr>
		<% end %>
	</table>
  </div>
  <div class="col-6">
  	<h1>Terminadas :D!</h1>
  	<table>
		<tr>
			<th> Título </th>
			<th> Descripción </th>
		</tr>
		<% @todos.where(completed: true).each do |todo| %>
		<tr>
			<td> <%= todo.title %> </td>
			<td> <%= todo.description %> </td>
			<td> <%= link_to "Ver", todo_path(todo.id) %> </td>
			<td> <%= link_to "Editar", edit_todo_path(todo.id) %> </td>
			<td> <%= link_to "Eliminar", todo_path(todo.id), method: :delete, data: { confirm: '¿Estás seguro de eliminar tarea?'} %> </td>
			<td> <%= link_to "Terminar tarea", task_done_path(todo.id) %> </td>
		</tr>
		<% end %>
	</table>
  </div>
</div>

app/views/todos/new.html.erb
<h1> Crear un nuevo pendiente ʕ•ᴥ•ʔ </h1>

<%= render 'form' %>

app/views/todos/show.html.erb
<h1> Vista de ToDo <%= @todo.title %> </h1>
<p> <%= @todo.description %></p>

<!-- metodo que muestra si la tarea esta completa o no -->
<% if @todo.completed == true %>
	<h4> ¡Yay! la has terminado :D! </h4>

<% else %>
	<h4> Esta tarea aún está pendiente :( </h4>
<% end %>